In [3]:
# importing numpy

import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


# Diemensions

In [25]:
arr1 = np.array([[1,2,3,56,7,53,24,5,6],[3,5,3,4,3,2,6,7,8]])

In [27]:
print(arr1.ndim)

2


In [29]:
arr1

array([[ 1,  2,  3, 56,  7, 53, 24,  5,  6],
       [ 3,  5,  3,  4,  3,  2,  6,  7,  8]])

In [41]:
arr1 = np.array([[[1,2,3,56,7,53,24,5,6],[3,5,3,4,3,2,6,7,8],[,5,6,3,4,6,3,6,8,4,2])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1841043292.py, line 1)

In [33]:
print(arr1.ndim)

3


In [61]:
arr2 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])

In [63]:
print(arr2.ndim)

3


In [69]:
arr5 = np.identity((4))

In [71]:
1
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
arr6 = np.linspace(10,20,4)
print(arr6)

[10.         13.33333333 16.66666667 20.        ]


In [77]:
arr2

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [79]:
arr5

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [75]:
arr5 = arr2.copy()
arr5

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [81]:
arr5.shape

(1, 3, 3)

In [83]:
arr1.shape

(1, 1, 0)

In [87]:
three_d = np.array([[[12,34,33],[2,34,22]],[[12,34,33],[2,34,22]]])

In [89]:
three_d.ndim

3

In [91]:
print(three_d)

[[[12 34 33]
  [ 2 34 22]]

 [[12 34 33]
  [ 2 34 22]]]


In [93]:
four_d = np.array([[[[12,34,33],[2,34,22]],[[12,34,33],[2,34,22]]]])

In [95]:
four_d

array([[[[12, 34, 33],
         [ 2, 34, 22]],

        [[12, 34, 33],
         [ 2, 34, 22]]]])

In [97]:
four_d.size

12

In [99]:
four_d.itemsize

4

# LIST VS ARRAY

In [104]:
a=range(100)
a

range(0, 100)

In [110]:
list1 = np.arange(100)
list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [106]:
import sys

In [116]:
print(sys.getsizeof(1)*len(list1))

2800


In [120]:
print(arr1.itemsize*arr1.size)

0


In [140]:
new_arr = np.arange(24).reshape(6,4)

In [142]:
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [172]:
new_arr[2:4][0][1:3]

array([ 9, 10])

In [176]:
rows:rows, columns : columns

new_arr[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [178]:
new_arr[4:6, 0:2]

array([[16, 17],
       [20, 21]])

In [184]:
new_arr[2:6, 1:3]

array([[ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [186]:
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [192]:
lower_dim  = new_arr.ravel()

In [194]:
lower_dim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [196]:
lower_dim.ndim

1

In [202]:
#transpose =>  convert rows to columns and columns to rows
a = new_arr.transpose()
a

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [210]:
a.shape

(4, 6)

In [212]:
new_arr.shape

(6, 4)

In [214]:
#STAKINGGGG!!!!!!!!!!!!!!!!!!!!!!!!!!
# horizontal stake (columns)
# verticla stake (rows)


In [216]:
a = np.arange(12).reshape(3,4)

In [218]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [228]:
b = np.arange(12).reshape(3,4)

In [232]:
b*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [236]:
b = b*3

In [238]:
b

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [240]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

In [242]:
np.hstack((b,a))

array([[ 0,  3,  6,  9,  0,  1,  2,  3],
       [12, 15, 18, 21,  4,  5,  6,  7],
       [24, 27, 30, 33,  8,  9, 10, 11]])

In [244]:
np.hstack((a,a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [246]:
np.hstack((b,b))

array([[ 0,  3,  6,  9,  0,  3,  6,  9],
       [12, 15, 18, 21, 12, 15, 18, 21],
       [24, 27, 30, 33, 24, 27, 30, 33]])

In [248]:
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [250]:
np.vstack((a,a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [258]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [262]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]