In [3]:
import numpy as np

In [5]:
thirty_eliments = np.arange(30)

In [7]:
thirty_eliments

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
thirty_eliments.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [13]:
thirty_eliments.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [19]:
rows = thirty_eliments.reshape(5,6)

## rows

In [25]:
# retrive 2 and3 rows
rows[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [35]:
rows[2:4,1:5]

array([[13, 14, 15, 16],
       [19, 20, 21, 22]])

In [45]:
rows[0:4,1:4]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [49]:
rows

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [117]:
rows[0:6, 1:6:2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [121]:
rows[0:6:2, 1:6:2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [127]:
rows.size

30

In [129]:
#memory allocation
rows.itemsize

4

In [131]:
rows.ndim

2

In [133]:
rows.dtype

dtype('int32')

In [180]:
rows

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [143]:
# for iterator in terable

for i in np.nditer(rows):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [155]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [149]:
arr2

array([ 3,  4, 65, 32,  4,  5,  6])

In [151]:
arr1

array([ 2,  3,  5,  6,  7, 34,  5])

In [157]:
print(arr1*arr1)

[ 1  4  9 16 25 36]


In [159]:
2*arr1

array([ 2,  4,  6,  8, 10, 12])

In [162]:
2**arr1

array([ 2,  4,  8, 16, 32, 64], dtype=int32)

In [166]:
arr1>=3

array([False, False,  True,  True,  True,  True])

In [170]:
arr2.dot(arr1)

154

In [172]:
arr1.max()

6

In [174]:
arr1.min()

1

In [178]:
## row wise min and max


1


In [182]:
rows.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [ ]:
rows.max(axis=0)